# Generated by Django 5.0.6 on 2024-05-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caravansApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caravanimages',
            name='image',
            field=models.ImageField(default='null', upload_to='images/'),
            preserve_default=False,
        ),
    ]
