# Generated by Django 5.0.6 on 2024-11-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caravansApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caravan',
            name='engine',
            field=models.CharField(default=None, max_length=63, verbose_name='Silnik'),
        ),
        migrations.AddField(
            model_name='caravan',
            name='horse_power',
            field=models.IntegerField(default=None, verbose_name='Konie Mechaniczne'),
        ),
    ]
