# Generated by Django 5.0.6 on 2025-01-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caravansApp', '0002_caravan_engine_caravan_horse_power'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageform',
            name='endDate',
            field=models.DateField(blank=True, null=True, verbose_name='Data końcowa'),
        ),
        migrations.AddField(
            model_name='messageform',
            name='startDate',
            field=models.DateField(blank=True, null=True, verbose_name='Data początkowa'),
        ),
        migrations.AlterField(
            model_name='caravan',
            name='description',
            field=models.TextField(verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='caravan',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='caravan',
            name='seating',
            field=models.CharField(max_length=63, verbose_name='Liczba miejsc'),
        ),
        migrations.AlterField(
            model_name='caravan',
            name='transmission',
            field=models.CharField(max_length=63, verbose_name='Skrzynia biegów'),
        ),
        migrations.AlterField(
            model_name='caravan',
            name='year_of_production',
            field=models.IntegerField(verbose_name='Rok produkcji'),
        ),
        migrations.AlterField(
            model_name='caravanimages',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='Zdjęcia'),
        ),
        migrations.AlterField(
            model_name='messageform',
            name='message',
            field=models.CharField(max_length=511, verbose_name='Wiadomość'),
        ),
        migrations.AlterField(
            model_name='messageform',
            name='name',
            field=models.CharField(max_length=254, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='messageform',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Numer telefonu'),
        ),
    ]
