# Generated by Django 5.0.6 on 2024-05-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caravansApp', '0002_caravanimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caravan',
            name='description',
            field=models.TextField(),
        ),
    ]
