# Generated by Django 5.0.6 on 2024-06-29 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caravansApp', '0003_alter_caravan_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caravanimages',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
