# Generated by Django 5.0.6 on 2025-01-26 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caravansApp', '0003_messageform_enddate_messageform_startdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messageform',
            old_name='endDate',
            new_name='dataend',
        ),
        migrations.RenameField(
            model_name='messageform',
            old_name='startDate',
            new_name='datastart',
        ),
    ]
