# Generated by Django 5.0.6 on 2024-08-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caravansApp', '0004_alter_caravanimages_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MassageForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('email', models.CharField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('massage', models.TextField()),
            ],
        ),
    ]
