# Generated by Django 5.0.6 on 2024-08-06 11:33

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caravansApp', '0005_massageform'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Date')),
                ('email', models.CharField(max_length=254)),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('message', models.TextField(verbose_name='Message')),
            ],
        ),
        migrations.DeleteModel(
            name='MassageForm',
        ),
        migrations.AlterField(
            model_name='calendar',
            name='date',
            field=django.contrib.postgres.fields.ranges.DateRangeField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='caravan',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='caravan',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='caravanimages',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='Image'),
        ),
    ]
