# Generated by Django 5.0.6 on 2024-08-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caravansApp', '0008_remove_calendar_date_calendar_caravan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caravan',
            name='seating',
            field=models.CharField(default='Null', max_length=63, verbose_name='Seatings'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caravan',
            name='transmission',
            field=models.CharField(default='Null', max_length=63, verbose_name='transmission'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caravan',
            name='year_of_production',
            field=models.IntegerField(default=2020, verbose_name='year'),
            preserve_default=False,
        ),
    ]
